"""learning_log URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

# import functions and module that manage URLs for project/admin
# NOTE, when autogenerated, import include was not there
from django.conf.urls import include, url
from django.contrib import admin

# url patterns determined by body of file
# urlpatterns include sets of URLs from apps in the project
urlpatterns = [
    # admin.site.urls defines all the urls that can be requested from admin
    url(r'^admin/', include(admin.site.urls)),
    # match any url that starts with word users, and made a namespace for ease
    url(r'^users/', include('users.urls', namespace='users')),
    # included module learning_logs.url and a namespace argument to distinguish
    # learning_logs's URLs from other URLs.
    url(r'', include('learning_logs.urls', namespace='learning_logs')),

]
